# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

conv <- function(h, x) {
    .Call('rwirelesscom_conv', PACKAGE = 'rwirelesscom', h, x)
}

sinc <- function(x) {
    .Call('rwirelesscom_sinc', PACKAGE = 'rwirelesscom', x)
}

rcosine <- function(x, B, Ns) {
    .Call('rwirelesscom_rcosine', PACKAGE = 'rwirelesscom', x, B, Ns)
}

rrcosine <- function(x, B, Ns) {
    .Call('rwirelesscom_rrcosine', PACKAGE = 'rwirelesscom', x, B, Ns)
}

